/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import javax.swing.JOptionPane;

/**
 *
 * @author tutu5
 */
public class MiniCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form MiniCalculadora
     */
    public MiniCalculadora() {
        initComponents();
        this.setResizable(false);
    }

                   
        double a;
        double b;
        String operador;
    public class calcu implements Calcu{

        
        private double primerNumero;
        private double segundoNumero;
        private double suma;
        private double resta;
        private double multiplicacion;
        private double division;
        
        public calcu(double primerNumero, double segundoNumero) {
        this.primerNumero = primerNumero;
        this.segundoNumero = segundoNumero;
        }
        
        public double getPrimerNumero() {
            return primerNumero;
        }

        public void setPrimerNumero(double primerNumero) {
            this.primerNumero = primerNumero;
        }

        public double getSegundoNumero() {
            return segundoNumero;
        }

        public void setSegundoNumero(double segundoNumero) {
            this.segundoNumero = segundoNumero;
        }

        public double getSuma() {
            return suma;
        }

        public double getResta() {
            return resta;
        }


        public double getMultiplicacion() {
            return multiplicacion;
        }

        public double getDivision() {
            return division;
        }
        
        
        
        @Override
        public void suma() {
            suma = primerNumero + segundoNumero;
        }

        @Override
        public void resta() {
            resta = primerNumero - segundoNumero;
        }

        @Override
        public void multiplicacion() {
            multiplicacion = primerNumero * segundoNumero;
        }

        @Override
        public void division() {
            division = primerNumero / segundoNumero;
        }
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        rSButtonHover3 = new rojerusan.RSButtonHover();
        rSButtonHover6 = new rojerusan.RSButtonHover();
        rSButtonHover7 = new rojerusan.RSButtonHover();
        rSButtonHover27 = new rojerusan.RSButtonHover();
        txt_casilla = new javax.swing.JTextField();
        rSButtonHover8 = new rojerusan.RSButtonHover();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover9 = new rojerusan.RSButtonHover();
        rSButtonHover28 = new rojerusan.RSButtonHover();
        rSButtonHover10 = new rojerusan.RSButtonHover();
        rSButtonHover11 = new rojerusan.RSButtonHover();
        rSButtonHover12 = new rojerusan.RSButtonHover();
        rSButtonHover13 = new rojerusan.RSButtonHover();
        rSButtonHover14 = new rojerusan.RSButtonHover();
        rSButtonHover15 = new rojerusan.RSButtonHover();
        rSButtonHover16 = new rojerusan.RSButtonHover();
        rSButtonHover17 = new rojerusan.RSButtonHover();
        rSButtonHover29 = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonHover3.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover3.setText("/");
        rSButtonHover3.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 50));

        rSButtonHover6.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover6.setText("*");
        rSButtonHover6.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 50));

        rSButtonHover7.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover7.setText("C");
        rSButtonHover7.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover7ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 50));

        rSButtonHover27.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover27.setText("-");
        rSButtonHover27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover27ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 80, 50));

        txt_casilla.setEditable(false);
        txt_casilla.setBackground(new java.awt.Color(102, 102, 102));
        txt_casilla.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        txt_casilla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_casilla.setBorder(null);
        jPanel3.add(txt_casilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 350, 80));

        rSButtonHover8.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover8.setText("7");
        rSButtonHover8.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 50));

        rSButtonHover4.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover4.setText("8");
        rSButtonHover4.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, 50));

        rSButtonHover9.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover9.setText("9");
        rSButtonHover9.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 80, 50));

        rSButtonHover28.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover28.setText("=");
        rSButtonHover28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover28ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 80, 110));

        rSButtonHover10.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover10.setText("4");
        rSButtonHover10.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 50));

        rSButtonHover11.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover11.setText("5");
        rSButtonHover11.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, 50));

        rSButtonHover12.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover12.setText("6");
        rSButtonHover12.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover12ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 50));

        rSButtonHover13.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover13.setText("1");
        rSButtonHover13.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover13ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 50));

        rSButtonHover14.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover14.setText("2");
        rSButtonHover14.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover14ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 50));

        rSButtonHover15.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover15.setText("3");
        rSButtonHover15.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover15ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 80, 50));

        rSButtonHover16.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover16.setText("0");
        rSButtonHover16.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover16ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 170, 50));

        rSButtonHover17.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover17.setText(".");
        rSButtonHover17.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonHover17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover17ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 80, 50));

        rSButtonHover29.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover29.setText("+");
        rSButtonHover29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover29ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 80, 110));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover16ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"0");
    }//GEN-LAST:event_rSButtonHover16ActionPerformed

    private void rSButtonHover13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover13ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"1");
    }//GEN-LAST:event_rSButtonHover13ActionPerformed

    private void rSButtonHover14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover14ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"2");
    }//GEN-LAST:event_rSButtonHover14ActionPerformed

    private void rSButtonHover15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover15ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"3");
    }//GEN-LAST:event_rSButtonHover15ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"4");
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"5");
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover12ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"6");
    }//GEN-LAST:event_rSButtonHover12ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"7");
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"8");
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        this.txt_casilla.setText(this.txt_casilla.getText()+"9");
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover7ActionPerformed
        this.txt_casilla.setText("");
    }//GEN-LAST:event_rSButtonHover7ActionPerformed

    private void rSButtonHover29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover29ActionPerformed

        a = doublevalidat(this.txt_casilla.getText());
        this.operador = "+";
        this.txt_casilla.setText("");
    }//GEN-LAST:event_rSButtonHover29ActionPerformed

    private void rSButtonHover28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover28ActionPerformed

        b = doublevalidat(this.txt_casilla.getText());
        double suma;
        double resta;
        double multiplicacion;
        double division;
        calcu calcu = new calcu(a, b);
        calcu.suma();
        calcu.resta();
        calcu.multiplicacion();
        calcu.division();
        
        suma = calcu.getSuma();
        resta = calcu.getResta();
        multiplicacion = calcu.getMultiplicacion();
        division = calcu.getDivision();
        
        try{
        
        switch(this.operador){

            case "+": 
                this.txt_casilla.setText(sincero(suma));
                break;
            case "-":
                this.txt_casilla.setText(sincero(resta));
                break;  
            case "*":
                this.txt_casilla.setText(sincero(multiplicacion));
                break;
            case "/": 
                if (b == 0) {
                this.txt_casilla.setText("No se divide entre '0'");
            }else{
                
                this.txt_casilla.setText(sincero(division));
                break;
                    
            }          
        }
            
        }catch(Exception e){
            
        }   
        
    }//GEN-LAST:event_rSButtonHover28ActionPerformed

    public String sincero(double resultado){
        String retorno = "";
        retorno = Double.toString(resultado);
        if (resultado%1 == 0) {
            retorno = retorno.substring(0, retorno.length()-2);
        }
        return retorno;
    }
    
    private void rSButtonHover27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover27ActionPerformed
        a = doublevalidat(this.txt_casilla.getText());
        this.operador = "-";
        this.txt_casilla.setText("");
    }//GEN-LAST:event_rSButtonHover27ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        a = doublevalidat(this.txt_casilla.getText());
        this.operador = "*";
        this.txt_casilla.setText("");
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        a = doublevalidat(this.txt_casilla.getText());
        this.operador = "/";
        this.txt_casilla.setText("");
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover17ActionPerformed
        if ((!this.txt_casilla.getText().contains("."))) {
            this.txt_casilla.setText(this.txt_casilla.getText()+".");
        }
    }//GEN-LAST:event_rSButtonHover17ActionPerformed

    
        public double doublevalidat(String number){
        double result = 0;
        try{
            if (number !=null) {
                result = Double.parseDouble(number);
            }
            
        }catch(NumberFormatException nfe){
            //*No es numerico
        }
        return result;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private rojerusan.RSButtonHover rSButtonHover10;
    private rojerusan.RSButtonHover rSButtonHover11;
    private rojerusan.RSButtonHover rSButtonHover12;
    private rojerusan.RSButtonHover rSButtonHover13;
    private rojerusan.RSButtonHover rSButtonHover14;
    private rojerusan.RSButtonHover rSButtonHover15;
    private rojerusan.RSButtonHover rSButtonHover16;
    private rojerusan.RSButtonHover rSButtonHover17;
    private rojerusan.RSButtonHover rSButtonHover27;
    private rojerusan.RSButtonHover rSButtonHover28;
    private rojerusan.RSButtonHover rSButtonHover29;
    private rojerusan.RSButtonHover rSButtonHover3;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover6;
    private rojerusan.RSButtonHover rSButtonHover7;
    private rojerusan.RSButtonHover rSButtonHover8;
    private rojerusan.RSButtonHover rSButtonHover9;
    private javax.swing.JTextField txt_casilla;
    // End of variables declaration//GEN-END:variables
}
